BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "User" (
	"UserID"	INTEGER,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	PRIMARY KEY("UserID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Groups" (
	"GroupID"	INTEGER,
	"GroupName"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("GroupID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GroupList" (
	"GroupID"	INTEGER,
	"UserID"	INTEGER,
	FOREIGN KEY("UserID") REFERENCES "User"("UserID"),
	FOREIGN KEY("GroupID") REFERENCES "Groups"("GroupID")
);
CREATE TABLE IF NOT EXISTS "FriendsList" (
	"UserID"	INTEGER NOT NULL,
	"FriendID"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "Tasks" (
	"TaskID"	INTEGER,
	"CreatedDate"	TEXT NOT NULL,
	"TaskTitle"	TEXT NOT NULL,
	"TaskDescription"	TEXT,
	"StartDate"	TEXT,
	"EndDate"	TEXT,
	PRIMARY KEY("TaskID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TaskList" (
	"ListID"	INTEGER,
	"TaskID"	INTEGER NOT NULL,
	"UserGroupID"	INTEGER NOT NULL,
	FOREIGN KEY("UserGroupID") REFERENCES "GroupList"("GroupID"),
	PRIMARY KEY("ListID" AUTOINCREMENT),
	FOREIGN KEY("TaskID") REFERENCES "Tasks"("TaskID")
);
INSERT INTO "Groups" VALUES (2,'Tesslkadjst');
COMMIT;
